### ISSUE TITLE
Rainmeter: 4.0.0: Plugin: Unable to load "\TopProcesses.dll" (error 126) (64bit)

### ISSUE THREAD

**Issue by matswat** [mistic100/Rainmeter-TopProcesses#1]
Rainmeter: 4.0.0 r2746 64-bit (Jan  1 2017) is NOT loading TopProcesses.dll (64bit), making skins based on this plugin not usable.

Rainmeter log:
[MeasureTopCPU]: Plugin: Unable to load "\TopProcesses.dll" (error 126)

System spec:
System: Windows 7 Professional 64-bit (build 7601) Service Pack 1

**Comment by mistic100** [comment]
I updated to the final release of Rainmeter 4 (same as you) and my skin https://github.com/mistic100/Rainmeter-GalaxyS works perfectly.

Please note that I am not the author of this plugin, the only build I found from the original author was not working since Rainmeter 3.2
So if not already done, please download the DLL from this repository and replace it in your Rainmeter directory.
